name = "garmin-webhook"
main = "src/index.js"
compatibility_date = "2025-01-15"

# Environment variables (set these in Cloudflare dashboard or wrangler)
# SUPABASE_URL
# SUPABASE_SERVICE_KEY
# GARMIN_CONSUMER_KEY
# GARMIN_CONSUMER_SECRET
# GARMIN_WEBHOOK_SECRET (optional)

# Free plan automatically gets 10ms CPU limit
# Paid plan ($5/month) gets 30s CPU limit

# Or use workers.dev subdomain for free
# URL will be: https://garmin-webhook.<your-subdomain>.workers.dev
