name = "garmin-webhook"
main = "src/index.js"
compatibility_date = "2025-01-15"

# Environment variables (set these in Cloudflare dashboard or wrangler)
# SUPABASE_URL
# SUPABASE_SERVICE_KEY
# GARMIN_CONSUMER_KEY
# GARMIN_CONSUMER_SECRET
# GARMIN_WEBHOOK_SECRET (optional)

# Workers limits
[limits]
cpu_ms = 10000

# For production deployment
[env.production]
routes = [
  { pattern = "garmin-webhook.tribos.studio/*", zone_name = "tribos.studio" }
]

# Or use workers.dev subdomain for free
# URL will be: https://garmin-webhook.<your-subdomain>.workers.dev
